### ISSUE TITLE
Compatibility of Signing & Verification with V2 Component Descriptors

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm#201]
**Description**
We have to check whether the OCM-based signing and verification process works also with V2 ("CNUDIE") Component Descriptors. Background is that we need to support the V2 CDs with the OCM Toolset, so that we can safely exchange the "non-OCM Toolset" with the OCM Toolset in existing scenarios.

**Done Criteria**
- [ ] It has been verified that V2-CD can be signed and verified using the OCM Toolset

**Comment by jensh007** [comment]
Signing with ocm and verifying with component-cli is not compatible:

```
ocm sign component -s jens -K $KEY ghcr.io/jensh007//github.com/acme/simpleserver

component-cli ca signatures verify rsa ghcr.io/jensh007 github.com/acme/simpleserver 1.0.0 --signature-name jens --public-key /Users/d058463/Documents/SAP-Dev/Kubernetes/ocm/getting-started/acme.pub

unable to create rsa verifier: unable to parse public key: asn1: structure error: tags don't match (6 vs {class:2 tag:0 length:3 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} ObjectIdentifier @2
```

**Comment by jensh007** [comment]
There are more incompatibilities:

```
component-cli ca signatures sign rsa ghcr.io/jensh007 github.com/acme/simpleserver 0.1.0 --upload-base-url ghcr.io/jensh007/signed --recursive --signature-name jens2 --private-key private-key.pem
unable to to fetch component descriptor github.com/acme/simpleserver:0.1.0: unknown component config type 'application/vnd.ocm.software.component.config.v1+json' expected 'application/vnd.gardener.cloud.cnudie.component.config.v1+json'
```

```
component-cli ca remote push gen/ca      
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104c182a8]

goroutine 1 [running]:
github.com/gardener/component-spec/bindings-go/apis/v2.FromUnstructuredObject(0x10530fc58, 0x140001c3780, 0x0, 0x10530fbb8, 0x140001df0e0, 0x0, 0x0)
	/go/src/github.com/gardener/component-cli/vendor/github.com/gardener/component-spec/bindings-go/apis/v2/codecs.go:195 +0x28
github.com/gardener/component-spec/bindings-go/apis/v2.(*UnstructuredTypedObject).DecodeInto(...)
	/go/src/github.com/gardener/component-cli/vendor/github.com/gardener/component-spec/bindings-go/apis/v2/unstructured.go:118
github.com/gardener/component-cli/pkg/components.GetOCIRepositoryContext(0x10530fc30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1400003ceb0, 0x47)
	/go/src/github.com/gardener/component-cli/pkg/components/localcache.go:118 +0x244
github.com/gardener/component-cli/pkg/components.OCIRef(0x10530fc30, 0x0, 0x14000039db8, 0x16, 0x14000690a90, 0x5, 0x10532cb68, 0x140000f5180, 0x10531b790, 0x140001a3700)
	/go/src/github.com/gardener/component-cli/pkg/components/localcache.go:103 +0x3c
github.com/gardener/component-cli/pkg/commands/componentarchive/remote.(*PushOptions).Run(0x140006cc4d0, 0x105321f68, 0x140003c7e60, 0x1053266a0, 0x140001c2da0, 0x0, 0x105332208, 0x10590e030, 0x105321f68, 0x104fd264a)
	/go/src/github.com/gardener/component-cli/pkg/commands/componentarchive/remote/push.go:98 +0x278
github.com/gardener/component-cli/pkg/commands/componentarchive/remote.NewPushCommand.func1(0x1400001cb00, 0x1400009ca20, 0x1, 0x1)
	/go/src/github.com/gardener/component-cli/pkg/commands/componentarchive/remote/push.go:64 +0xbc
github.com/spf13/cobra.(*Command).execute(0x1400001cb00, 0x1400009ca00, 0x1, 0x1, 0x1400001cb00, 0x1400009ca00)
	/go/src/github.com/gardener/component-cli/vendor/github.com/spf13/cobra/command.go:863 +0x1d0
github.com/spf13/cobra.(*Command).ExecuteC(0x140001c9080, 0x1400018e000, 0x140001c9080, 0x104773e84)
	/go/src/github.com/gardener/component-cli/vendor/github.com/spf13/cobra/command.go:977 +0x264
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/gardener/component-cli/vendor/github.com/spf13/cobra/command.go:905
main.main()
	/go/src/github.com/gardener/component-cli/cmd/component-cli/main.go:20 +0x70
```

**Comment by In-Ko** [comment]
Looking at both examples above, I wonder whether we have to support scenarios where the component-cli is used on OCM generated artifacts (first example is signing with OCM and verifying with component-cli, second example is signing an OCM-generated CD with the component-cli).

Wouldn't it be enough if we focus on using the OCM on artifacts created with the component-cli, and not vice versa ? The OCM-CLI being able to work with existing V2-CDs would enable all stakeholders to move to the new tooling. Why should stakeholders need to use the V2-Toolset ("component-cli") on V3 CDs (created via OCM-CLI) ?

**Comment by In-Ko** [comment]
As per our discussion:
- Existing and signed V2 (component-cli based) components must be verifiable with OCM-CLI

**Comment by jensh007** [comment]
Status Update: 

- Performed several tests with ocm and component-cli to verify Gardener components:
- Two issues identified and fixed

**Comment by jensh007** [comment]
Issue: component-cli adds in normalized cd the field "extraIdentity":null even if this field is not present in the source
Needs an update of ocm to handle this.
Fix tested with test component successfully (sign with component-cli, verify with ocm)

**Comment by jensh007** [comment]
couple of fixes applied:

- successfully verified Gardener BoM now
- successfully resigned Gardener BoM with ocm and verified it again.
- PR and merge outstanding

**Comment by In-Ko** [comment]
Can this be closed ? Are all currently known compatibility-related things fixed ?
