### ISSUE TITLE
Nilpointer during ocm download component

### ISSUE THREAD

**Issue by robertgraeff** [open-component-model/ocm#708]
**What happened**:

Hi,

I tried to download a component version with the command

```shell
ocm download component eu.gcr.io/gardener-project/landscaper/examples//github.com/gardener/landscaper-examples/helm-deployer/helm-1:v0.1.0 -O ./archive
```

It failed with the following nilpointer error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x320d6a4]

goroutine 1 [running]:
github.com/open-component-model/ocm/pkg/contexts/ocm/transfer.copyVersion({0x0, 0x0}, {0x4142e90, 0xc00062b700}, {0xc00036a220, 0x1, 0x1}, {0x4163a88, 0xc000c01800}, {0x4163920, ...}, ...)
	/Users/d032864/hub/git/ocm/ocm/pkg/contexts/ocm/transfer/transfer.go:289 +0x1084
github.com/open-component-model/ocm/pkg/contexts/ocm/transfer.CopyVersion({0x0, 0x0}, {0x4142e90, 0xc00062b700}, {0xc00036a220, 0x1, 0x1}, {0x4163a88?, 0xc000c01800?}, {0x4163920, ...}, ...)
	/Users/d032864/hub/git/ocm/ocm/pkg/contexts/ocm/transfer/transfer.go:218 +0xf6
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/components/download.(*action).Save(0xc00075ae80, 0xc000033340, {0x7ff7bfeff5e6, 0xc})
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/commands/ocmcmds/components/download/cmd.go:147 +0x4cd
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/components/download.(*action).Out(0xc00075ae80)
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/commands/ocmcmds/components/download/cmd.go:113 +0x190
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.HandleOutput({0x411ad90, 0xc00075ae80}, {0x411c9a0, 0xc000a37860}, {0xc0004f5890?, 0x1, 0x0?})
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/pkg/utils/handling.go:102 +0x2a6
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/components/download.(*Command).Run(0xc0007b79c0)
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/commands/ocmcmds/components/download/cmd.go:83 +0x328
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.SetupCommand.func1(0xc0001bf600?, {0xc000d84570, 0x1, 0x3})
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/pkg/utils/command.go:194 +0x12e
github.com/spf13/cobra.(*Command).execute(0xc000c4a600, {0xc0001121b0, 0x3, 0x3})
	/Users/d032864/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:943 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007dcf00)
	/Users/d032864/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:1071 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x4155350?)
	/Users/d032864/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:995 +0x13
main.main()
	/Users/d032864/hub/git/ocm/ocm/cmds/ocm/main.go:21 +0xdc
```

Actually, the component descriptor was downloaded, but the `blobs` directory was empty.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Just try to run the command. The component version still exists.

**Anything else we need to know**:

Here you can find the component constructor that I used to create the component version:
[component-constructor.yaml](https://github.com/gardener/landscaper-examples/blob/master/helm-deployer/helm-1/commands/component-constructor.yaml)

**Environment**:

OCM version (latest commit of the main branch):
```json
{"Major":"0", "Minor":"9", "Patch":"0", "PreRelease":"dev", "Meta":"09e73686933678cc5ec9335d8b6e8c10fc3a7021", "GitVersion":"0.9.0-dev+09e73686933678cc5ec9335d8b6e8c10fc3a7021", "GitCommit":"09e73686933678cc5ec9335d8b6e8c10fc3a7021", "GitTreeState":"dirty", "BuildDate":"2024-03-22T07:38:21+0000", "GoVersion":"go1.21.5", "Compiler":"gc", "Platform":"darwin/amd64"}
```

**Comment by morri-son** [comment]
@mandelsoft @hilmarf Regression?

**Comment by Skarlso** [comment]
@robertgraeff Which version of OCM are you using?
