### ISSUE TITLE
unhandled nil-pointer-dereference (ocm list componentversions)

### ISSUE THREAD

**Issue by ccwienk** [open-component-model/ocm#864]
**What happened**
```
$ ocm list componentversions example.com/my-component:1.0.0 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2850cf2]

goroutine 1 [running]:
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr.(*TypeHandler).all(0xc00150a6c0, {0x0, 0x0})
	/home/runner/work/ocm/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go:88 +0x32
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr.(*TypeHandler).get(0xc00150a6c0, {0x0, 0x0}, {0x3794780?, 0xc000417390?})
	/home/runner/work/ocm/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go:213 +0x885
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr.(*TypeHandler).Get(0x37958c0?, {0x3794780?, 0xc000417390?})
	/home/runner/work/ocm/ocm/cmds/ocm/commands/ocmcmds/common/handlers/vershdlr/typehandler.go:109 +0x31
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.HandleOutput({0x37bcba0, 0xc00002c5b0}, {0x37bdfe0, 0xc00150a6c0}, {0xc000417380?, 0x3?, 0xc00150a6c0?})
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/handling.go:84 +0x1c4
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.HandleOutputs(...)
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/handling.go:64
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.HandleArgs(0xc00008fea0, {0x37bdfe0, 0xc00150a6c0}, {0xc000417230, 0x1, 0x0?})
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/handling.go:60 +0xeb
github.com/open-component-model/ocm/cmds/ocm/commands/ocmcmds/components/list.(*Command).Run(0xc000c168c0)
	/home/runner/work/ocm/ocm/cmds/ocm/commands/ocmcmds/components/list/cmd.go:79 +0x2bd
github.com/open-component-model/ocm/cmds/ocm/pkg/utils.SetupCommand.func1(0xc000247700?, {0xc000417230, 0x1, 0x1})
	/home/runner/work/ocm/ocm/cmds/ocm/pkg/utils/command.go:190 +0x130
github.com/spf13/cobra.(*Command).execute(0xc00025b808, {0xc0000720b0, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:943 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006e6308)
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:1071 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x38023a0?)
	/home/runner/go/pkg/mod/github.com/open-component-model/cobra@v0.0.0-20230329075350-b1fd876abfb9/command.go:995 +0x13
main.main()
	/home/runner/work/ocm/ocm/cmds/ocm/main.go:17 +0xdc
```

**What you expected to happen**: a nice error-message

**How to reproduce it (as minimally and precisely as possible)**: see above

**Anything else we need to know**: flat is better than nested.

**Environment**: 
```
$ uname -a
Linux arch 6.10.0-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000 x86_64 GNU/Linux
```

```$ ocm version
{"Major":"0", "Minor":"12", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.12.0", "GitCommit":"e5ca3001323b75ee5793a786089f1f410e9e8db3", "GitTreeState":"", "BuildDate":"2024-07-19T14:21:12Z", "GoVersion":"go1.22.2", "Compiler":"gc", "Platform":"linux/amd64"}
```

**Comment by mandelsoft** [comment]
Hi @ccwienk , 
It tried this command with v0.12.0 and it works fine, there is the error message `Error: error processing "example.com/my-component:1.0.0": component version "example.com/my-component:1.0.0" not found`.

May be you have configured a default repository in you ocm config. Could you cross-check please and add this configuration to this issue..

**Comment by mandelsoft** [comment]
Ok, the error happens, if there is a resolver defined in your config.

The fix to provide an appropriate error is simple, but there is a problem provide the expected correct non-error result for the list command.

A resolver is able to resolve component versions. But here only a component is specified. Therefore the resolver cannot provide a result, and the output would be an error. Nevertheless, the expected result would be to get all the versions  potentially addressable by the given resolvers.

Unfortunately this is not yet possible. I still have to think about a possible solution for this.
